addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.6.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"       % "1.1.2")
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.11")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"  % "2.5")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"   % "0.6.28")
